### ISSUE TITLE
Contact Page Form 

### ISSUE THREAD

**Issue by kenan-memis** [ldanielswakman/nttd-design#2]
Hi,

Ceren told me that in contact page form all fields will be visible without clicking any button. Add telephone number, add job title and add company info buttons are unnecessary, just show all the fields at page reload.

Regards

**Comment by kenan-memis** [comment]
Also if it is Ok for you after working and updating your repository if possible also update your server, http://www.ldaniel.eu/nttd/index.php. I am comparing the current state of your design with my local work while working continously.  It is good for me :)

**Comment by ldanielswakman** [comment]
Regarding the contact form: this is a UX improvement I have been talking about with Ceren before: instead of a user having to go over about 10 fields to send a message, it would be easier if only the 'essential' fields were shown (subject, message, name, email) and someone can add more optional fields if they would want to. Same goes for sending a message from the Trade directory company page.

I'll update my server version whenever I can; just now it's not easy because I was doing much of the work offline and had just synced my github repo :)

**Comment by kenan-memis** [comment]
you are right Daniel, for a contact form email and message is enough I guess but I do not have any idea what did you talk with Ceren previously. Yesterday she saw it and she told me about it. But okey, it is her problem, if you talked previously just like this then you do not have to do anything. 

But again while you are making major changes it is better to understand each other, if she will want to change something later.

For server issue, sorry for that. I do not want to make you hurry. You can update whenever you can. I will continue to follow your github repo.

Today I applied to my local works your latest work. We are already synchronized. But as I mentioned yesterday, missing PAGES are important for me. If you can please add blank, dummy pages as Disclaimer page initially, later you can finish with the specific design. By doing so, I can complete the main layout and make the connections between the pages. Blank but working page link is better than missing page link :)

Thank you.
